/-
Proof library root: theorems about `Tiramemsu` definitions. The only library that may import
Mathlib; never linked into an executable.
-/
import TiramemsuProofs.Store.Order
import TiramemsuProofs.Store.Model
import TiramemsuProofs.Store.Interval
import TiramemsuProofs.Store.Merge
import TiramemsuProofs.Store.Reads
import TiramemsuProofs.Store.Walk
import TiramemsuProofs.Store.ModelOps
import TiramemsuProofs.Store.Invariant
import TiramemsuProofs.Store.OpSpec
import TiramemsuProofs.Store.TxInv
import TiramemsuProofs.Store.Transact
import TiramemsuProofs.Store.Oblivious
import TiramemsuProofs.Store.Speculation
import TiramemsuProofs.Store.Lifecycle
import TiramemsuProofs.Store.Views
import TiramemsuProofs.Store.Footprint
import TiramemsuProofs.Store.Cascade
import TiramemsuProofs.Store.Temporal
import TiramemsuProofs.Store.Effects
import TiramemsuProofs.Store.Assert
import TiramemsuProofs.Store.SupersedeProof
import TiramemsuProofs.Codec.ObjectId
import TiramemsuProofs.Codec.ShortStr
import TiramemsuProofs.Codec.Civil
import TiramemsuProofs.Codec.DateTime
import TiramemsuProofs.Codec.Range
import TiramemsuProofs.Codec.Text
import TiramemsuProofs.Codec.Integer
import TiramemsuProofs.Codec.Decimal
import TiramemsuProofs.Codec.Skolem
import TiramemsuProofs.Codec.Double.Basic
import TiramemsuProofs.Codec.Double.Parse
import TiramemsuProofs.Codec.Double.Interval
import TiramemsuProofs.Codec.Double.Print
import TiramemsuProofs.Codec.Double.RoundTrip
import TiramemsuProofs.Codec.Encode
import TiramemsuProofs.Term.Dict
import TiramemsuProofs.Codec.Laws
import TiramemsuProofs.Query.Rows
import TiramemsuProofs.Query.JoinLaws
import TiramemsuProofs.Query.DenoteJoin
import TiramemsuProofs.Query.Validate
import TiramemsuProofs.Query.Order
import TiramemsuProofs.Query.Aggregate
import TiramemsuProofs.Query.Scan
import TiramemsuProofs.Query.Stable
import TiramemsuProofs.Query.EvRun
import TiramemsuProofs.Query.Inlj
import TiramemsuProofs.Query.Pushdown
import TiramemsuProofs.Query.JoinCore
import TiramemsuProofs.Query.OrderLimit
import TiramemsuProofs.Query.EvalDenote
import TiramemsuProofs.Query.EvalSim
import TiramemsuProofs.Query.EvalDenoteTop
import TiramemsuProofs.Path.Lang
import TiramemsuProofs.Path.Dfa
import TiramemsuProofs.Path.Expr
import TiramemsuProofs.Path.Fuel
import TiramemsuProofs.Path.Spec
import TiramemsuProofs.Path.Reach
import TiramemsuProofs.Path.Trail
import TiramemsuProofs.Path.Inverse
import TiramemsuProofs.Path.Graph
import TiramemsuProofs.Path.Timed
import TiramemsuProofs.Path.TimedBound
import TiramemsuProofs.Path.Shortest
import TiramemsuProofs.Path.ShortestKey
