/-
Format-1 DDL: the statements of the pinned Rust `ddl_v1.sql`, split as Rust's
`split_statements` splits them (comments stripped, trigger bodies whole). GENERATED by
`scripts/gen-ddl.py` from Rust commit cb53154a90445bd13d6e41b77a3db94744ea3a83; do not edit. Shell module.
-/

namespace Tiramemsu.Storage

--# @lat: [[codec#Storage Format 1#Schema]]

/-- The format-1 statements, in creation order. -/
def ddlV1 : Array String := #[
  "CREATE TABLE meta (\n  key   TEXT PRIMARY KEY,\n  value INTEGER NOT NULL\n) STRICT;",
  "CREATE TABLE term (\n  id   INTEGER PRIMARY KEY,   \n  tag  INTEGER NOT NULL,      \n  lex  TEXT NOT NULL,\n  dt   INTEGER,               \n  lang TEXT,                  \n  num  REAL                   \n) STRICT;",
  "CREATE UNIQUE INDEX term_key ON term(tag, lex, ifnull(dt, 0), ifnull(lang, ''));",
  "CREATE INDEX term_num ON term(num) WHERE num IS NOT NULL;",
  "CREATE TABLE tx (\n  t       INTEGER PRIMARY KEY,\n  instant INTEGER NOT NULL\n) STRICT;",
  "CREATE UNIQUE INDEX tx_instant ON tx(instant);",
  "CREATE TABLE triple (\n  eid      INTEGER PRIMARY KEY,  \n  s        INTEGER NOT NULL,\n  p        INTEGER NOT NULL,\n  o        INTEGER NOT NULL,\n  t_add    INTEGER NOT NULL,\n  t_ret    INTEGER,              \n  v_from   INTEGER,              \n  v_to     INTEGER,              \n  ret_kind INTEGER               \n) STRICT;",
  "CREATE INDEX live_spo ON triple(s, p, o, t_ret, v_from, v_to) WHERE t_ret IS NULL;",
  "CREATE INDEX live_pos ON triple(p, o, s, t_ret, v_from, v_to) WHERE t_ret IS NULL;",
  "CREATE INDEX live_osp ON triple(o, s, p, t_ret, v_from, v_to) WHERE t_ret IS NULL;",
  "CREATE INDEX hist_spo ON triple(s, p, o, t_add DESC, t_ret, v_from, v_to);",
  "CREATE INDEX hist_pos ON triple(p, o, s, t_add DESC, t_ret, v_from, v_to);",
  "CREATE INDEX hist_osp ON triple(o, s, p, t_add DESC, t_ret, v_from, v_to);",
  "CREATE INDEX valid_p ON triple(p, v_from, v_to) WHERE t_ret IS NULL;",
  "CREATE INDEX log_add ON triple(t_add);",
  "CREATE INDEX log_ret ON triple(t_ret, ret_kind) WHERE t_ret IS NOT NULL;",
  "CREATE TABLE volatile (\n  s          INTEGER NOT NULL,\n  key        INTEGER NOT NULL,\n  value      INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  PRIMARY KEY (s, key)\n) WITHOUT ROWID, STRICT;",
  "CREATE TABLE pred_multi (\n  p INTEGER PRIMARY KEY          \n) STRICT;",
  "CREATE VIEW event(t, eid, op, kind) AS\n  SELECT t_add, eid, 'assert', NULL FROM triple\n  UNION ALL\n  SELECT t_ret, eid, 'retract', ret_kind FROM triple WHERE t_ret IS NOT NULL;",
  "CREATE TRIGGER triple_no_delete BEFORE DELETE ON triple\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: triples are never deleted'); END;",
  "CREATE TRIGGER triple_retract_once BEFORE UPDATE ON triple\nWHEN OLD.t_ret IS NOT NULL\n  OR NEW.eid IS NOT OLD.eid OR NEW.s IS NOT OLD.s OR NEW.p IS NOT OLD.p\n  OR NEW.o IS NOT OLD.o OR NEW.t_add IS NOT OLD.t_add\n  OR NEW.v_from IS NOT OLD.v_from OR NEW.v_to IS NOT OLD.v_to\n  OR NEW.t_ret IS NULL\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: only a single retraction is allowed'); END;",
  "CREATE TRIGGER triple_no_replace BEFORE INSERT ON triple\nWHEN EXISTS (SELECT 1 FROM triple WHERE eid = NEW.eid)\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: eids are never reused'); END;",
  "CREATE TRIGGER term_no_replace BEFORE INSERT ON term\nWHEN EXISTS (SELECT 1 FROM term WHERE id = NEW.id)\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: term ids are never reused'); END;",
  "CREATE TRIGGER tx_no_replace BEFORE INSERT ON tx\nWHEN EXISTS (SELECT 1 FROM tx WHERE t = NEW.t)\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: transaction numbers are never reused'); END;",
  "CREATE TRIGGER term_no_delete BEFORE DELETE ON term\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: terms are never deleted'); END;",
  "CREATE TRIGGER term_no_update BEFORE UPDATE ON term\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: terms are immutable'); END;",
  "CREATE TRIGGER tx_no_delete BEFORE DELETE ON tx\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: transactions are never deleted'); END;",
  "CREATE TRIGGER tx_no_update BEFORE UPDATE ON tx\nBEGIN SELECT RAISE(ABORT, 'tiramemsu: transactions are immutable'); END;"
]

end Tiramemsu.Storage
