#!/usr/bin/env python3
"""Generates src/Tiramemsu/Storage/Ddl.lean from the pinned Rust ddl_v1.sql (read with
`git show`, the Rust repository is never written), split exactly as Rust's
`storage::split_statements` splits it.

  scripts/gen-ddl.py            write the Lean file
  scripts/gen-ddl.py --check    fail if the checked-in file differs (drift)
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUST = os.environ.get("TIRAMEMSU_RUST_REPO", os.path.join(ROOT, "tiramemsu"))
OUT = os.path.join(ROOT, "src", "Tiramemsu", "Storage", "Ddl.lean")


def pin():
    for line in open(os.path.join(ROOT, "oracle", "RUST_PIN")):
        if line.startswith("commit"):
            return line.split("=", 1)[1].strip()
    raise SystemExit("no commit in oracle/RUST_PIN")


def split_statements(sql):
    """A line-for-line port of Rust's split_statements."""
    out, cur, in_str, i = [], "", False, 0
    while i < len(sql):
        c = sql[i]
        i += 1
        if in_str:
            cur += c
            if c == "'":
                in_str = False
            continue
        if c == "'":
            in_str = True
            cur += c
        elif c == "-" and i < len(sql) and sql[i] == "-":
            while i < len(sql):
                d = sql[i]
                i += 1
                if d == "\n":
                    cur += "\n"
                    break
        elif c == ";":
            cur += ";"
            t = cur.strip()
            upper = t.upper()
            is_trigger = upper.startswith("CREATE TRIGGER")
            if not is_trigger or upper.rstrip(";").rstrip().endswith("END"):
                if t != ";":
                    out.append(t)
                cur = ""
        else:
            cur += c
    if cur.strip():
        out.append(cur.strip())
    return out


def lean_string(s):
    r = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return '"' + r + '"'


def render(commit, stmts):
    lines = [
        "/-",
        "Format-1 DDL: the statements of the pinned Rust `ddl_v1.sql`, split as Rust's",
        "`split_statements` splits them (comments stripped, trigger bodies whole). GENERATED by",
        f"`scripts/gen-ddl.py` from Rust commit {commit}; do not edit. Shell module.",
        "-/",
        "",
        "namespace Tiramemsu.Storage",
        "",
        "--# @lat: [[codec#Storage Format 1#Schema]]",
        "",
        "/-- The format-1 statements, in creation order. -/",
        "def ddlV1 : Array String := #[",
    ]
    lines += ["  " + lean_string(s) + ("," if k + 1 < len(stmts) else "") for k, s in enumerate(stmts)]
    lines += ["]", "", "end Tiramemsu.Storage", ""]
    return "\n".join(lines)


def main():
    commit = pin()
    sql = subprocess.run(["git", "-C", RUST, "show", f"{commit}:crates/tm-core/src/storage/ddl_v1.sql"],
                         check=True, capture_output=True, text=True).stdout
    text = render(commit, split_statements(sql))
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            sys.exit("src/Tiramemsu/Storage/Ddl.lean differs from the pinned Rust ddl_v1.sql (run scripts/gen-ddl.py)")
        print("ddl ok: src/Tiramemsu/Storage/Ddl.lean matches the pinned Rust ddl_v1.sql")
    else:
        open(OUT, "w").write(text)
        print(f"wrote {OUT}")


main()
